export const FETCH_ALL_TABLE_DATA = "FETCH_ALL_TABLE_LIST";

export const SET_PLATFORM_LIST = "SET_PLATFORM_LIST";
export const SET_CATEGORY_LIST = "SET_CATEGORY_LIST";
export const SET_TECHNOLOGY_LIST = "SET_TECHNOLOGY_LIST";
export const SET_LANGUAGE_LIST = "SET_LANGUAGE_LIST";
export const SET_SOCIAL_LIST = "SET_SOCIAL_LIST";
export const SET_COMPANY_SIZE = "SET_COMPANY_SIZE";
export const SET_PAGE_SIZE = "SET_PAGE_SIZE";
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
export const SET_SORT = "SET_SORT";
export const SET_SEARCH = "SET_SEARCH";
export const SET_KEYWORD_SEARCH = "SET_KEYWORD_SEARCH";

export const SET_INSTAGRAM = "SET_INSTAGRAM";
export const SET_FACEBOOK = "SET_FACEBOOK";
export const SET_TWITTER = "SET_TWITTER";
export const SET_YOUTUBE = "SET_YOUTUBE";
export const SET_PINTRESS = "SET_PINTRESS";
export const SET_TIKTOK = "SET_TIKTOK";

export const FILTER_PLATFORM_LIST = "FILTER_PLATFORM_LIST";

export const SET_TECHNOLOGY_NAMES = "SET_TECHNOLOGY_NAMES";
export const SET_TECHNOLOGY_TYPES = "SET_TECHNOLOGY_TYPES";
export const FILTER_TECHNOLOGY_NAMES = "FILTER_TECHNOLOGY_NAMES";
export const FILTER_TECHNOLOGY_TYPES = "FILTER_TECHNOLOGY_TYPES";

export const FILTER_CATEGORY_LIST = "FILTER_CATEGORY_LIST";
export const FILTER_SOCIAL_LIST = "FILTER_SOCIAL_LIST";

export const SET_INSTAGRAM_FILTER = "SET_INSTAGRAM_FILTER";
export const SET_FACEBOOK_FILTER = "SET_FACEBOOK_FILTER";
export const SET_TWITTER_FILTER = "SET_TWITTER_FILTER";
export const SET_YOUTUBE_FILTER = "SET_YOUTUBE_FILTER";
export const SET_PINTEREST_FILTER = "SET_PINTEREST_FILTER";
export const SET_TIKTOK_FILTER = "SET_TIKTOK_FILTER";

export const FILTER_FACEBOOK_FILTER = "FILTER_FACEBOOK_FILTER";
export const FILTER_INSTAGRAM_FILTER = "FILTER_INSTAGRAM_FILTER";
export const FILTER_TWITTER_FILTER = "FILTER_TWITTER_FILTER";
export const FILTER_YOUTUBE_FILTER = "FILTER_YOUTUBE_FILTER";
export const FILTER_PINTEREST_FILTER = "FILTER_PINTEREST_FILTER";
export const FILTER_TIKTOK_FILTER = "FILTER_TIKTOK_FILTER";

export const SET_COMPANY_SIZE_FILTER = "SET_COMPANY_SIZE_FILTER";
export const FILTER_COMPANY_SIZE_FILTER = "FILTER_COMPANY_SIZE_FILTER";
export const CLEAR_ALL_FILTER_DATA = "CLEAR_ALL_FILTER_DATA";
